bases:
  - ../../base/

resources:
  - ingress.yml

images:
  - name: app-image
    newName: ${containerImageUri}

namespace: ${namespace}

configMapGenerator:
  - name: app-runtime
    literals:
      - SPRING_PROFILES_ACTIVE=prod
