apiVersion: v1
kind: Service
metadata:
  name: i046364-eks-hello
  labels:
    app: i046364-eks-hello
spec:
  ports:
    - name: http
      port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app: i046364-eks-hello
